# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_spot', models.IntegerField()),
                ('time_range', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.IntegerField(default='')),
                ('lat', models.IntegerField(default='')),
                ('radius', models.CharField(max_length=100)),
                ('occupied', models.BooleanField(default=False)),
            ],
        ),
    ]
