# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 02:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20170412_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spots',
            name='radius',
        ),
    ]
