# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_remove_spots_radius'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='lat',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='spots',
            name='lng',
            field=models.IntegerField(default=''),
        ),
    ]
