# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20170412_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spots',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='spots',
            name='lng',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
